CREATE TABLE "COIN_USER" (
	"ID"	varchar2 (20)		NOT NULL,
	"PW"	varchar2 (20)		NOT NULL,
	"EMAIL"	varchar2 (50)		NOT NULL,
	"MONEY"	number(8)	DEFAULT 10000	NULL
);

CREATE TABLE "aCOIN" (
	"A_PRICE"	number(8)		NULL,
	"A_IDX"	number(8)		NULL
);
create SEQUENCE tbl_aCOIN_seq_idx 
start with 1 increment by 1 MINVALUE 1 MAXVALUE 3600 CYCLE; --a코인 시퀀스

CREATE TABLE "bCOIN" (
	"B_PRICE"	number(8)		NULL,
	"B_IDX"	number(8)		NULL
);
create SEQUENCE tbl_bCOIN_seq_idx 
start with 1 increment by 1 MINVALUE 1 MAXVALUE 3600 CYCLE; --a코인 시퀀스

CREATE TABLE "dCOIN" (
	"D_PRICE"	number(8)		NULL,
	"D_IDX"	number(8)		NULL
);
create SEQUENCE tbl_dCOIN_seq_idx 
start with 1 increment by 1 MINVALUE 1 MAXVALUE 3600 CYCLE; --a코인 시퀀스

CREATE TABLE "cCOIN" (
	"C_PRICE"	number(8)		NULL,
	"C_IDX"	number(8)		NULL
);
create SEQUENCE tbl_dCOIN_seq_idx 
start with 1 increment by 1 MINVALUE 1 MAXVALUE 3600 CYCLE; --a코인 시퀀스

CREATE TABLE "COIN_QNA" (
	"ID"	varchar2	(20)	NOT NULL,
	"SUBJECT"	varchar2	(100)	NULL,
	"CONTENTS"	varchar2	(1500)	NULL,
	"REGDATE"	date	DEFAULT sysdate	NULL,
	"ANSWER"	varchar2	(1500)	NULL
);

CREATE TABLE "aRECEIPT" (
	"A_ID"	varchar2	(20)	NOT NULL,
	"A_PRICE"	number(8)		NULL,
	"A_COUNT"	number(4)		NULL,
	"A_REGDATE"	date	DEFAULT sysdate	NULL
);

CREATE TABLE "bRECEIPT" (
	"B_ID"	varchar2	(20)	NOT NULL,
	"B_PRICE"	number(8)		NULL,
	"B_COUNT"	number(4)		NULL,
	"B_REGDATE"	date	DEFAULT sysdate	NULL
);

CREATE TABLE "cRECEIPT" (
	"C_ID"	varchar2	(20)	NOT NULL,
	"C_PRICE"	number(8)		NULL,
	"C_COUNT"	number(4)		NULL,
	"C_REGDATE"	date	DEFAULT sysdate	NULL
);

CREATE TABLE "dRECEIPT" (
	"D_ID"	varchar2	(20)	NOT NULL,
	"D_PRICE"	number(8)		NULL,
	"D_COUNT"	number(4)		NULL,
	"D_REGDATE"	date	DEFAULT sysdate	NULL
);

CREATE TABLE "COIN_MONEY" (
	"ID"	varchar2	(20)	NOT NULL,
	"REGDATE"	date	DEFAULT sysdate	NULL,
	"MONEY"	number(7)		NULL
);

ALTER TABLE "COIN_USER" ADD CONSTRAINT "PK_COIN_USER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "aCOIN" ADD CONSTRAINT "PK_ACOIN" PRIMARY KEY (
	"A_PRICE"
);

ALTER TABLE "bCOIN" ADD CONSTRAINT "PK_BCOIN" PRIMARY KEY (
	"B_PRICE"
);

ALTER TABLE "dCOIN" ADD CONSTRAINT "PK_DCOIN" PRIMARY KEY (
	"D_PRICE"
);

ALTER TABLE "cCOIN" ADD CONSTRAINT "PK_CCOIN" PRIMARY KEY (
	"C_PRICE"
);

ALTER TABLE "COIN_QNA" ADD CONSTRAINT "PK_COIN_QNA" PRIMARY KEY (
	"ID"
);

ALTER TABLE "aRECEIPT" ADD CONSTRAINT "PK_ARECEIPT" PRIMARY KEY (
	"A_ID",
	"A_PRICE"
);

ALTER TABLE "bRECEIPT" ADD CONSTRAINT "PK_BRECEIPT" PRIMARY KEY (
	"B_ID",
	"B_PRICE"
);

ALTER TABLE "cRECEIPT" ADD CONSTRAINT "PK_CRECEIPT" PRIMARY KEY (
	"C_ID",
	"C_PRICE"
);

ALTER TABLE "dRECEIPT" ADD CONSTRAINT "PK_DRECEIPT" PRIMARY KEY (
	"D_ID",
	"D_PRICE"
);

ALTER TABLE "COIN_MONEY" ADD CONSTRAINT "PK_COIN_MONEY" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COIN_QNA" ADD CONSTRAINT "FK_COIN_USER_TO_COIN_QNA_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "aRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_aRECEIPT_1" FOREIGN KEY (
	"A_ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "aRECEIPT" ADD CONSTRAINT "FK_aCOIN_TO_aRECEIPT_1" FOREIGN KEY (
	"A_PRICE"
)
REFERENCES "aCOIN" (
	"A_PRICE"
);

ALTER TABLE "bRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_bRECEIPT_1" FOREIGN KEY (
	"B_ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "bRECEIPT" ADD CONSTRAINT "FK_bCOIN_TO_bRECEIPT_1" FOREIGN KEY (
	"B_PRICE"
)
REFERENCES "bCOIN" (
	"B_PRICE"
);

ALTER TABLE "cRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_cRECEIPT_1" FOREIGN KEY (
	"C_ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "cRECEIPT" ADD CONSTRAINT "FK_cCOIN_TO_cRECEIPT_1" FOREIGN KEY (
	"C_PRICE"
)
REFERENCES "cCOIN" (
	"C_PRICE"
);

ALTER TABLE "dRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_dRECEIPT_1" FOREIGN KEY (
	"D_ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "dRECEIPT" ADD CONSTRAINT "FK_dCOIN_TO_dRECEIPT_1" FOREIGN KEY (
	"D_PRICE"
)
REFERENCES "dCOIN" (
	"D_PRICE"
);

ALTER TABLE "COIN_MONEY" ADD CONSTRAINT "FK_COIN_USER_TO_COIN_MONEY_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

