CREATE TABLE "COIN_USER" (
	"ID"	varchar2(20)		NOT NULL,
	"PW"	varchar2(50)		NOT NULL,
	"EMAIL1"	varchar2(50)		NOT NULL,
	"EMAIL2"	varchar2(50)		NULL,
	"MONEY"	number(8)	DEFAULT 10000	NULL,
	"REGDATE"	date	DEFAULT sysdate	NULL,
	"EMAILCHECK"	NUMBER(1)	DEFAULT 0	NULL,
	"PWCHECK"	NUMBER(1)	DEFAULT 1	NULL
);

CREATE TABLE "COIN_QNA" (
	"ID"	varchar2(20)		NOT NULL,
	"SUBJECT"	varchar2(500)		NULL,
	"CONTENTS"	varchar2(1500)		NULL,
	"REGDATE"	date	DEFAULT sysdate	NULL,
	"ANSWER"	varchar2(1500)		NULL
);

CREATE TABLE "COIN_MONEY" (
	"ID"	varchar2(20)		NOT NULL,
	"REGDATE"	date	DEFAULT sysdate	NULL,
	"MONEY"	number(7)		NULL
);

CREATE TABLE "COIN_RECEIPT" (
	"ID"	varchar2(20)		NOT NULL,
	"NUM"	NUMBER(1)		NULL,
	"COUNT"	number(4)		NULL,
	"REGDATE"	date	DEFAULT sysdate	NULL,
	"PRICE"	number(8)		NULL
);

CREATE TABLE "COIN_PRICE" (
	"NUM"	NUMBER(1)		NULL,
	"TIME"	date		NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

CREATE TABLE "COIN_LIST" (
	"NUM"	NUMBER(1)		NULL,
	"NAME"	VARCHAR(4)		NULL
);

ALTER TABLE "COIN_USER" ADD CONSTRAINT "PK_COIN_USER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COIN_QNA" ADD CONSTRAINT "PK_COIN_QNA" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COIN_MONEY" ADD CONSTRAINT "PK_COIN_MONEY" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COIN_RECEIPT" ADD CONSTRAINT "PK_COIN_RECEIPT" PRIMARY KEY (
	"ID",
	"NUM"
);

ALTER TABLE "COIN_PRICE" ADD CONSTRAINT "PK_COIN_PRICE" PRIMARY KEY (
	"NUM"
);

ALTER TABLE "COIN_LIST" ADD CONSTRAINT "PK_COIN_LIST" PRIMARY KEY (
	"NUM"
);

ALTER TABLE "COIN_QNA" ADD CONSTRAINT "FK_COIN_USER_TO_COIN_QNA_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "COIN_MONEY" ADD CONSTRAINT "FK_COIN_USER_TO_COIN_MONEY_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "COIN_RECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_COIN_RECEIPT_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "COIN_RECEIPT" ADD CONSTRAINT "FK_COIN_LIST_TO_COIN_RECEIPT_1" FOREIGN KEY (
	"NUM"
)
REFERENCES "COIN_LIST" (
	"NUM"
);

ALTER TABLE "COIN_PRICE" ADD CONSTRAINT "FK_COIN_LIST_TO_COIN_PRICE_1" FOREIGN KEY (
	"NUM"
)
REFERENCES "COIN_LIST" (
	"NUM"
);
