CREATE TABLE "COIN_USER" (
	"ID"	varchar2(20)		NOT NULL,
	"PW"	varchar2(50)		NOT NULL,
	"EMAIL1"	varchar2(50)		NOT NULL,
	"EMAIL2"	varchar2(50)		NULL,
	"MONEY"	number(8)	DEFAULT 10000	NULL,
	"REGDATE"	date	DEFAULT sysdate	NULL
);

CREATE TABLE "COIN_QNA" (
	"ID"	varchar2(20)		NOT NULL,
	"SUBJECT"	varchar2(500)		NULL,
	"CONTENTS"	varchar2(1500)		NULL,
	"REGDATE"	date	DEFAULT sysdate	NULL,
	"ANSWER"	varchar2(1500)		NULL
);

CREATE TABLE "COIN_MONEY" (
	"ID"	varchar2(20)		NOT NULL,
	"REGDATE"	date	DEFAULT sysdate	NULL,
	"MONEY"	number(7)		NULL
);

CREATE TABLE "aRECEIPT" (
	"A_ID"	varchar2(20)		NOT NULL,
	"A_COUNT"	number(4)		NULL,
	"A_REGDATE"	date	DEFAULT sysdate	NULL,
	"A_PRICE"	number(8)		NULL
);

CREATE TABLE "bRECEIPT" (
	"B_ID"	varchar2(20)		NOT NULL,
	"B_COUNT"	number(4)		NULL,
	"B_REGDATE"	date	DEFAULT sysdate	NULL,
	"B_PRICE"	number(8)		NULL
);

CREATE TABLE "dRECEIPT" (
	"D_ID"	varchar2(20)		NOT NULL,
	"D_COUNT"	number(4)		NULL,
	"D_REGDATE"	date	DEFAULT sysdate	NULL,
	"D_PRICE"	number(8)		NULL
);

CREATE TABLE "cRECEIPT" (
	"C_ID"	varchar2(20)		NOT NULL,
	"C_COUNT"	number(4)		NULL,
	"C_REGDATE"	date	DEFAULT sysdate	NULL,
	"C_PRICE"	number(8)		NULL
);

CREATE TABLE "ACOIN" (
	"TIME"	date		NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

CREATE TABLE "BCOIN" (
	"TIME"	date		NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

CREATE TABLE "CCOIN" (
	"TIME"	date		NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

CREATE TABLE "DCOIN" (
	"TIME"	date		NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

ALTER TABLE "COIN_USER" ADD CONSTRAINT "PK_COIN_USER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COIN_QNA" ADD CONSTRAINT "PK_COIN_QNA" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COIN_MONEY" ADD CONSTRAINT "PK_COIN_MONEY" PRIMARY KEY (
	"ID"
);

ALTER TABLE "aRECEIPT" ADD CONSTRAINT "PK_ARECEIPT" PRIMARY KEY (
	"A_ID"
);

ALTER TABLE "bRECEIPT" ADD CONSTRAINT "PK_BRECEIPT" PRIMARY KEY (
	"B_ID"
);

ALTER TABLE "dRECEIPT" ADD CONSTRAINT "PK_DRECEIPT" PRIMARY KEY (
	"D_ID"
);

ALTER TABLE "cRECEIPT" ADD CONSTRAINT "PK_CRECEIPT" PRIMARY KEY (
	"C_ID"
);

ALTER TABLE "COIN_QNA" ADD CONSTRAINT "FK_COIN_USER_TO_COIN_QNA_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "COIN_MONEY" ADD CONSTRAINT "FK_COIN_USER_TO_COIN_MONEY_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "aRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_aRECEIPT_1" FOREIGN KEY (
	"A_ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "bRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_bRECEIPT_1" FOREIGN KEY (
	"B_ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "dRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_dRECEIPT_1" FOREIGN KEY (
	"D_ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "cRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_cRECEIPT_1" FOREIGN KEY (
	"C_ID"
)
REFERENCES "COIN_USER" (
	"ID"
);


