CREATE TABLE "COIN_USER" (
	"ID"	varchar2(20)		NOT NULL,
	"PW"	varchar2(50)		NOT NULL,
	"EMAIL1"	varchar2(50)		NOT NULL,
	"EMAIL2"	varchar2(50)		NOT NULL,
	"MONEY"	number(8)	DEFAULT 10000	NOT NULL,
	"REGDATE"	date	DEFAULT sysdate	NOT NULL
);

CREATE TABLE "COIN_QNA" (
	"ID"	varchar2(20)		NOT NULL,
	"SUBJECT"	varchar2(500)		NOT NULL,
	"CONTENTS"	varchar2(1500)		NOT NULL,
	"REGDATE"	date	DEFAULT sysdate	NOT NULL,
	"ANSWER"	varchar2(1500)		NULL
);

CREATE TABLE "COIN_MONEY" (
	"ID"	varchar2(20)		NOT NULL,
	"REGDATE"	date	DEFAULT sysdate	NOT NULL,
	"MONEY"	number(7)		NOT NULL
);

CREATE TABLE "aRECEIPT" (
	"ID"	varchar2(20)		NOT NULL,
	"COUNT"	number(4)		NOT NULL,
	"REGDATE"	date	DEFAULT sysdate	NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

CREATE TABLE "bRECEIPT" (
	"ID"	varchar2(20)		NOT NULL,
	"COUNT"	number(4)		NOT NULL,
	"REGDATE"	date	DEFAULT sysdate	NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

CREATE TABLE "dRECEIPT" (
	"ID"	varchar2(20)		NOT NULL,
	"COUNT"	number(4)		NOT NULL,
	"REGDATE"	date	DEFAULT sysdate	NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

CREATE TABLE "cRECEIPT" (
	"ID"	varchar2(20)		NOT NULL,
	"COUNT"	number(4)		NOT NULL,
	"REGDATE"	date	DEFAULT sysdate	NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

CREATE TABLE "ACOIN" (
	"TIME"	date		NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

CREATE TABLE "BCOIN" (
	"TIME"	date		NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

CREATE TABLE "CCOIN" (
	"TIME"	date		NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

CREATE TABLE "DCOIN" (
	"TIME"	date		NOT NULL,
	"PRICE"	number(8)		NOT NULL
);

ALTER TABLE "COIN_USER" ADD CONSTRAINT "PK_COIN_USER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "COIN_QNA" ADD CONSTRAINT "FK_COIN_USER_TO_COIN_QNA_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "COIN_MONEY" ADD CONSTRAINT "FK_COIN_USER_TO_COIN_MONEY_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "aRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_aRECEIPT_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "bRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_bRECEIPT_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "dRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_dRECEIPT_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);

ALTER TABLE "cRECEIPT" ADD CONSTRAINT "FK_COIN_USER_TO_cRECEIPT_1" FOREIGN KEY (
	"ID"
)
REFERENCES "COIN_USER" (
	"ID"
);


